spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ## http://localhost:8080/reals/fitness/openid-connect/
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: activity-service
          uri: lb://ACTIVITY-SERVICE
          predicates:
            - Path=/api/activities//Tracking**

        - id: ai-service
          uri: lb://AI_SERVICE
          predicates:
            - Path=/api/recom/**

server:
  port: 8181

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/