spring:

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessrecomm
      database: fitnessrecomm
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password:  # Replace this with your actual DB password

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


rabbitmq:
  exchange:
    name: fitness.exchange

  queue:
    name: activity.queue

  routing:
    key: activity.tracking

gemini:
  api:
   url: ## your GEMINI_API_url
   key: ## your GEMINI_KEY
